### ISSUE TITLE
Subscribe repos example?

### ISSUE THREAD

**Issue by Captain-Of-Coit** [sugyan/atrium#11]
Regarding atrium-api/src/com/atproto/sync/subscribe_repos.rs

It would be great to see some sort of example on how to use this. From brief reading of the code, it seems to not be implemented yet, as I cannot find anything regarding reading streams, events or anything like that. Is that correct?

**Comment by sugyan** [comment]
Unfortunately, the `subscription` feature is not yet implemented.
I would like to use it too and will do my best to implement it. 😵‍💫

**Comment by timfpark** [comment]
If it is helpful, I did some prototyping work with decoding the firehose here:  

https://github.com/timfpark/firehose-prototype/blob/main/src/main.rs

I've made it through the Header, Commit, and RepoOp structures after evaluating a bunch of CBOR deserializers and landing on `ciborium` in conjunction with `serde`. The principal challenge from here is decoding the CAR file in the commit as there does not seem to be an implementation of a CAR codec in Rust yet.  (There are versions in JS https://github.com/ipld/js-car and Go https://github.com/ipld/go-car).  Let me know if anyone knows about an existing CAR decoder implementation.

But it still should be possible to use this without block support for a large number of other scenarios like triggering on created posts, deleted follows, liked posts, etc. so probably ok deferring the CAR decode until later.

Hopefully this is helpful.

**Comment by sugyan** [comment]
Oooh very cool prototype implementation, thank you!
I will try to implement something like this with your codes as a reference!

**Comment by benwis** [comment]
Bisky has methods for reading records from the firehose that are working, see here: 
https://github.com/jesopo/bisky/tree/jess/firehose

**Comment by timfpark** [comment]
Also, I discovered a library for CAR in Rust here: https://github.com/dapplion/rs-car/tree/master

**Comment by sugyan** [comment]
I've merged #15 which includes `firehose` example.
There is still an issue with `images` embedding not being deserialized correctly, but I think it should work correctly for just extracting texts.
