### ISSUE TITLE
`atrium_xrpc_server` isn't compatible with `tokio::spawn`

### ISSUE THREAD

**Issue by str4d** [sugyan/atrium#20]
`atrium_xrpc_server::stream::frames::Frame::try_from` returns `Result<Self, Box<dyn std::error::Error>>`. The problem is that `dyn std::error::Error` is not `Send`, which means that if the result of `Frame::try_from` is potentially used across an await, the entire future is not `Send`.

To reproduce this, modify the firehose example to spawn the firehose running method instead of running it directly with `#[tokio::main]`. I tested this at commit 7d99ccd36c8bb562276732d1b9bb888f42530151.

It would be helpful if the error type was `Send + Sync + 'static`, to also make it compatible with the `anyhow` crate. But that can be handled by rewriting the error as a string, whereas the future not being `Send` is more problematic for usage.

**Comment by sugyan** [comment]
Thank you for your report! I modified `atrium-xrcp-server` to use `anyhow::Error` and confirmed that it works with the following change in `firehose` example.

```rust
    tokio::spawn(async move {
        let _ = process_message(&message).await;
    });
```
