### ISSUE TITLE
bsky_sdk::error::GenericXrpcError is not re-exported

### ISSUE THREAD

**Issue by oestradiol** [sugyan/atrium#220]
Hello guys!

Nice work you've been doing here <3

I wanted to ask if there's any good reason bsky_sdk::error::GenericXrpcError is not re-exported?
I'm struggling to find a way to read the status code, and, because it is not re-exported, I'm unfortunately having to resort to.. well...
![image](https://github.com/user-attachments/assets/fe223835-87aa-471c-93c7-236e6d058c33)
...this horrid thing LOL

Thanks ahead for the support!

**Comment by sugyan** [comment]
Thanks for using `bsky_sdk`!
And sorry for the inconvenience. It seems that I only made `Error` and `Result` public from `bsky_sdk::error` and forgot about `GenericXrpcError`.
I believe `bsky_sdk::error::GenericXrpcError` is now publicly accessible in 0.1.8, will this solve the inconvenience?

**Comment by oestradiol** [comment]
Oh, that was fast! And yes, it worked.
That's exactly what I needed, thank you very much!! My code is much happier now~
