### ISSUE TITLE
threadgate via agent.create_record doesn't apply to post

### ISSUE THREAD

**Issue by Blooym** [sugyan/atrium#249]
Hello,

I am trying to apply a threadgate to a post after I have made it by using `agent.create_record()` via `bsky_sdk`, but even though the record appears to be made correctly it does not actually apply to the post and comments are still enabled. The post data doesn't have a threadgate record attached either.

This is the short of what trying to do to achieve this. The real impl is [here](https://github.com/Blooym/skywrite/blob/cd688f65b48ad97508e026709942b65eaaf4cf85/src/bsky.rs#L99).

```rust
let record = agent
    .create_record(post::RecordData {
       . . .
    })
    .await.unwrap();

agent
    .create_record(threadgate::RecordData {
        allow: None,
        created_at: Datetime::now(),
        hidden_replies: None,
        post: record.uri.clone(),
    })
    .await.unwrap();
```

I'm going to assume this is user error, but I did see that threadgate is a supported KnownRecord so I assumed I was on the right path

**Comment by sugyan** [comment]
Hmmm... I didn't know this, but apparently the threadgate must have the same `rkey` as the post record.

Since `.create_record()` internally creates the record with the `rkey` set to `None`, I guess we need to explicitly specify the rkey using `com.atproto.repo.create_record` if I want to create a threadgate.
I have successfully applied threadgate with the following code:

```rust
let record = agent
    .create_record(post::RecordData {
       . . .
    })
    .await.unwrap();
let uri = record.uri.clone();
let rkey = uri.rsplit_once('/').map(|(_, rkey)| rkey.to_string());

let session = agent.get_session().await.ok_or(bsky_sdk::Error::NotLoggedIn)?;
agent
    .api
    .com
    .atproto
    .repo
    .create_record(
        atrium_api::com::atproto::repo::create_record::InputData {
            collection: atrium_api::app::bsky::feed::Threadgate::nsid(),
            record: atrium_api::app::bsky::feed::threadgate::RecordData {
                allow: Some(Vec::new()),
                created_at: Datetime::now(),
                hidden_replies: None,
                post: uri,
            }
            .try_into_unknown()?,
            repo: session.data.did.into(),
            rkey,
            swap_commit: None,
            validate: None,
        }
        .into(),
    )
    .await?;
```

**Comment by Blooym** [comment]
Thank you very much, this works perfectly
