### ISSUE TITLE
How can I delete reposts of a user?

### ISSUE THREAD

**Issue by klausi** [sugyan/atrium#253]
Hi, it's me again :)

I'm building a tool to delete all posts older than 90 days https://github.com/klausi/mastodon-bluesky-sync/blob/main/src/delete_posts.rs#L34

I already managed to implement the deletion of the author's own posts and now I would like to also delete reposts. The Javascript SDK has this as `agent.deleteRepost(uri)` https://docs.bsky.app/docs/tutorials/like-repost#un-reposting-a-post .

Is this already possible with the atrium library?

Thanks!

**Comment by klausi** [comment]
Yep, that was it! Checking if the post is a repost and using that URI works:
```rust
// Check if this post is a repost.
if let Some(viewer) = &post.post.viewer {
    if let Some(repost) = &viewer.repost {
        dates.insert(
            record.created_at.as_ref().clone().into(),
            repost.to_string(),
        );
        continue;
    }
}
```
Full code at https://github.com/klausi/mastodon-bluesky-sync/blob/main/src/delete_posts.rs

**Comment by sugyan** [comment]
Yes, reposted items have a URI in `.viewer.repost`, so we can delete them by passing it to `agent.delete_record()`. I would write the same code if I implemented it.
