### ISSUE TITLE
Video upload XRPCNotSupported 404 error

### ISSUE THREAD

**Issue by klausi** [sugyan/atrium#261]
Hi,

I'm trying to upload a video from my Mastodon sync tool:

```rust
let output = bsky_agent
                .api
                .app
                .bsky
                .video
                .upload_video(bytes.to_vec())
                .await
                .context(format!(
                    "Failed uploading video to Bluesky {}",
                    attachment.attachment_url
                ))?;
```
This returns an error:
```
Error posting to Bluesky: Error {
    context: "Failed uploading video to Bluesky https://files.mastodon.social/cache/media_attachments/files/113/561/819/830/868/286/original/e05a90a96ab2e71f.mp4",
    source: XrpcResponse(
        XrpcError {
            status: 404,
            error: Some(
                Undefined(
                    ErrorResponseBody {
                        error: Some(
                            "XRPCNotSupported",
                        ),
                        message: Some(
                            "XRPCNotSupported",
                        ),
                    },
                ),
            ),
        },
    ),
}
```

Full code is in https://github.com/klausi/mastodon-bluesky-sync/blob/bsky-video/src/post.rs#L276

Do you know what the problem might be? Thanks!

**Comment by sugyan** [comment]
Uploading video is not well documented yet (https://github.com/bluesky-social/bsky-docs/pull/227) and confusing, but `app.bsky.video.uploadVideo` is not available from BskyAgent.
This is a duplicate of #259 and `examples/video` has now been added, so please refer there.

**Comment by klausi** [comment]
Thanks for the quick help, as always! Added you to acknowledgements https://github.com/klausi/mastodon-bluesky-sync/blob/main/README.md#acknowledgements

The example makes sense, but is quite long. Should we build an API abstraction into Atrium? Ideally I want to pass the Bluesky Agent and some bytes to a function and it should do everything for me until the video is uploaded.

Also should the bsky_agent.api.app.bsky.video.upload_video() function be removed? It is confusing that it exists in the SDK when it does not work?

**Comment by sugyan** [comment]
Thanks for the suggestion. I have considered adding it as a method to `BskyAgent`, but have held off because I have determined that the specifications for video uploads are not yet documented and finalized.
I would be willing to add a method once the specification is documented in detail and implementation guidelines are provided.

With the background that many methods for XRPC requests are automatically generated from lexicon, It may be a bit difficult to remove only `bsky_agent.api.app.bsky.video.upload_video()`...

**Comment by klausi** [comment]
Ok thanks, I copied the video upload example into my program at https://github.com/klausi/mastodon-bluesky-sync/blob/main/src/bluesky_video.rs
