### ISSUE TITLE
How to convert PostView record to post::RecordData

### ISSUE THREAD

**Issue by lokxii** [sugyan/atrium#263]
`record` field in `atium_api::app::bsky::feed::defs::PostViewData` has type `atrium_api::types::Unknown`, which essentially is a `BTreeMap`.
There is a type `atrium_api::app::bsky::feed::post::RecordData` which represents a post record. Is there any way I can convert `Unknown` into `post::RecordData`?

**Comment by sugyan** [comment]
I recently added an example in the documentation, but it was not yet published as the latest version. My apologies.
https://github.com/sugyan/atrium/commit/3d117f32c93fa7ca184af79408cd940fca5795c7
Basically, `Unknown` is supposed to be converted to an arbitrary type using the `TryFromUnknown` trait.

**Comment by lokxii** [comment]
Nice! Just refactored a huge chunk of `BTreeMap` accessing crap with `TryFromUnknown`.
