### ISSUE TITLE
add rsky to the links in the readme

### ISSUE THREAD

**Issue by aeshna-cyanea** [sugyan/atrium#273]
rudy and co have been plugging away at rust tooling (including a PDS) for a while, would be a good idea to include them in the "related work". https://github.com/blacksky-algorithms/rsky

**Comment by erlend-sh** [comment]
Made a PR.

There should also be a way to show a ‘Used by’ widget in the gh sidebar, to preview this info: https://github.com/sugyan/atrium/network/dependents

**Comment by sugyan** [comment]
Thank you both for your suggestions and pull requests!
In the readme I wrote when I started creating the atrium project, I had only described the repository that I was referring to at the time.

As for the “Used by” widget, it seems to appear when there are dependencies from more than 100 repositories. Currently it is 84... so we are almost there :)
https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package
