### ISSUE TITLE
[suggestion] Consider making XrpcClient::auth return an owned value

### ISSUE THREAD

**Issue by pmsanford** [sugyan/atrium#29]
I've written a quick [example client](https://github.com/pmsanford/bluesky-example-client/blob/main/src/bsky/client.rs) to learn about the API. One feature I wanted for my client was to use interior mutability so that the client could refresh its tokens transparently to the consumer, even behind an immutable reference. As you can see, I used a mutex for this - but the fact that `auth` returns `Option<&str>` made that pretty difficult. It would also be difficult if you wanted to, for instance, retrieve a token from the environment dynamically in the auth method. My app runs against a branch in my fork that makes the simple change of returning `Option<String>` instead. You mentioned you were in the middle of refactoring this trait so I thought I'd make this suggestion now.

Thanks for all the work on this! It's been fun to use.

**Comment by sugyan** [comment]
Thanks for the suggestion! I agree exactly, and was just about to change it to `Option<String>` in the `XrpcClient` trait update on the branch I'm working on.
https://github.com/sugyan/atrium/commit/f7babd271059c1a9bd7b19998d6972839be220ae#diff-5847c85722dda4e0abdff0065313ae9cd4a2f6a167afda85cb90fa36a4fd3e3aL24-R23
(Other than that, I'm trying to move the dependencies that use `serde_json` and `serde_qs` from atrium-api and consolidate them into atrium-xrpc.)
