### ISSUE TITLE
Suggestion: Change code writer

### ISSUE THREAD

**Issue by icepuma** [sugyan/atrium#8]
Hey,
you folks could use a set of crates to assemble the generated code in a more structured manner:
* Use https://crates.io/crates/quote to write the individual pieces of code
* Use https://crates.io/crates/syn and https://crates.io/crates/proc-macro2 to have structs for pieces of `Ident`s for the struct names etc. and `TokenStream`
* Use https://crates.io/crates/prettyplease to pretty print the whole shebang

The basic idea:
1. Assemble lots of small `TokenStream`s to a large one
2. Convert `TokenStream` to `&str` using https://docs.rs/proc-macro2/1.0.56/proc_macro2/struct.TokenStream.html#method.to_string
3. Pipe the generated string through https://docs.rs/syn/2.0.15/syn/fn.parse_file.html to generate a https://docs.rs/syn/2.0.15/syn/struct.File.html
4. Pipe https://docs.rs/syn/2.0.15/syn/struct.File.html through https://docs.rs/prettyplease/0.2.4/prettyplease/fn.unparse.html to have a pretty printed `String`

Given this approach of having a `TokenStream` you get proper error messages, when something is not a legit AST token and you could add your own pretty printer, ...

If the idea is not clear enough, please ask :)

**Comment by sugyan** [comment]
Thanks for the great suggestion!
I've never implemented a code writer before, and I honestly thought I'd start with something that worked anyway, so I did it pretty crudely. I was going to rewrite it later to make it look better...

I'll try to rewrite it based on your suggestion!

**Comment by icepuma** [comment]
I don't know if this is "theeee" correct way to do it, but you get a free code formatter with it :D

**Comment by icepuma** [comment]
Hmm. Here's a quick one. I'm currently working on the same problem: 
> having a proper Rust version of the AT protocol

If you would love to have someone helping you working on `atrium`, I would be glad to help. I have some suggestions and some new code (axum server code to create a PDS), I would love to contribute.

If you like the idea, we could have a quick talk at Discord or via E-Mail.

**Comment by sugyan** [comment]
Thank you for your suggestion for contributions.
I personally am inclined to implement them at a leisurely pace while pondering the design on my own, but I should probably ask for help in moving the protocol implementation OSS project forward.
If you send me pull requests, I will do my best to review and test them.
